### ISSUE TITLE
Status 'ready' when connecting via Tor

### ISSUE THREAD

**Issue by KayBeSee** [LN-Zap/node-lnd-grpc#356]
I am struggling to connect to my node over Tor.

I have put in my lndconnect uri and run the minimal example but my status is stuck at `ready` with no errors being thrown.

It looks like Tor is starting up because `tor.isStarted` returns true. Any ideas?

```
import LndGrpc from 'lnd-grpc';

(async () => {

   const grpc = new LndGrpc({
       lndconnectUri: process.env.LND_CONNECT_URI
     });

   await grpc.connect();

   console.log(grpc.state); // returns 'ready'

   console.log(grpc.tor.isStarted()) // returns true
})

```

**Comment by rahulbile** [comment]
@KayBeSee can you confirm whats the lnd version and node-lnd-grpc version you are testing with ?

**Comment by KayBeSee** [comment]
I've tried with lnd versions `v0.12.1` and `v0.13.1-beta`

I am using ` "lnd-grpc": "^0.5.0"`.

This is the output I get when I run with DEBUG:

```
  lnrpc:torproc Sep 24 15:02:07.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits +462ms
  lnrpc:torproc Sep 24 15:02:07.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit +1ms
  lnrpc:torproc Sep 24 15:02:07.000 [notice] Bootstrapped 100% (done): Done +743ms
  lnrpc:service:State Connecting to State gRPC service +0ms
  lnrpc:service:State Establishing gRPC connection to State with proto file /Users/kevinmulcrone/repos/ln-test/node_modules/lnd-grpc/proto/0.13.1-beta/lnrpc/stateservice.proto and connection options { 'grpc.max_send_message_length': -1, 'grpc.max_receive_message_length': -1, 'grpc.keepalive_permit_without_calls': 1 } +20ms
  lnrpc:service:State Unable to connect to State service Error: Failed to connect before the deadline
    at checkState (/Users/kevinmulcrone/repos/ln-test/node_modules/lnd-grpc/node_modules/@grpc/grpc-js/build/src/client.js:73:26)
    at Timeout._onTimeout (/Users/kevinmulcrone/repos/ln-test/node_modules/lnd-grpc/node_modules/@grpc/grpc-js/build/src/channel.js:382:17)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) +30s
connected:  ready
(node:2938) UnhandledPromiseRejectionWarning: TypeError: Lightning.subscribeChannelEvents is not a function
    at /Users/kevinmulcrone/repos/ln-test/test.js:45:35
(node:2938) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2938) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by KayBeSee** [comment]
I've continued looking at this and noticed that the tests for tor are also failing when connecting. Same/similar output as above.

I noticed that the Zap Desktop app uses this library, so downloaded that and tried to connect to my nodes there but no luck.
