### ISSUE TITLE
trouble using Invoices.subscribeSingleInvoice({r_hash})

### ISSUE THREAD

**Issue by dmidnight** [LN-Zap/node-lnd-grpc#77]
I cannot seem to get this method to work.

I have tried providing r_hash as a base64 string, a hex string, and a Buffer, but no matter what, I always get the same response: 'invalid hash length of 0'

{ Error: invalid hash length of 0
    at Http2CallStream.call.on (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call.js:68:41)
     at Http2CallStream.emit (events.js:194:15)
    at process.nextTick (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
     at process._tickCallback (internal/process/next_tick.js:61:11)
   code: 2,
   details: 'invalid hash length of 0',
  metadata:
   Metadata {
      options: undefined,
      internalRepr: Map { 'content-type' => [Array] } } }

What might I be doing wrong, or how can I go about debugging this?

Thanks

**Comment by mrfelton** [comment]
Good catch, thanks. Merged.
